name: CI

on:
  push:
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Frontend deps
        working-directory: ./SpeakEasy/frontend
        run: npm i

      - name: Frontend tests
        working-directory: ./SpeakEasy/frontend
        run: npm run test

      - name: Backend deps
        working-directory: ./SpeakEasy/backend
        run: npm i

      - name: Backend tests
        working-directory: ./SpeakEasy/backend
        run: npm run test
