name: CI

on:
  push:
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm

      # ---------- Frontend ----------
      - name: Dependências de front-end
        working-directory: ./frontend
        run: npm install

      - name: Testes de front-end
        working-directory: ./frontend
        run: npm run test

      # ---------- Backend ----------
      - name: Dependências de backend
        working-directory: ./backend
        run: npm install

      - name: Testes de backend
        working-directory: ./backend
        run: npm run test
